language: node_js
node_js:
  - "stable"
cache:
  directories:
    - "node_modules"
script:
  - npm run lint
  - npm run test -- --ci --verbose --coverage
  - npm install codecov -g
after_success:
  - codecov