version: '3.7'

services:
  transport-event-module:
    container_name: transport-event-module
#    command: npm run test
    command: tail -f /dev/null
    build:
      context: ./docker
      dockerfile: Dockerfile
    tty: true
    volumes:
      - .:/app
